### ISSUE TITLE
How can I know the workflow diagram is rendered?

### ISSUE THREAD

**Issue by tlyau62** [optimajet/workflow-designer-javascript-sample#1]
May I ask is there any api for getting the rendered or created event, such that I can add a loading spinner?

e.g. $('wf-designer').on('wf::ready', () => {
  this.ready = true;
  // ...
})

**Comment by sergeythrees** [comment]
> May I ask is there any api for getting the rendered or created event, such that I can add a loading spinner?
> 
> e.g. $('wf-designer').on('wf::ready', () => { this.ready = true; // ... })

Hello, @tlyau62,
you can pass the "funcOnSuccess" callback to the function Designer.load(data, funcOnSuccess, funcOnError), it is triggered when the scheme is successfully loaded right before the render.

You can see the use of the Designer.load() function in the documentation for this example:
https://github.com/optimajet/workflow-designer-javascript-sample#get-started
```javascript
import WorkflowDesigner from '@optimajet/workflow-designer'
//import '@optimajet/workflow-designer/localization/workflowdesigner.localization_ru'

const data = {
    schemecode: "<YOUR_SCHEME_CODE_VALUE>",
    processid: undefined
};

var wfdesigner = new WorkflowDesigner({
    apiurl: '<YOUR_API_URL_VALUE>',
    renderTo: 'root',
    graphwidth: window.innerWidth,
    graphheight: window.innerHeight,
});

if (wfdesigner.exists(data)) {

    wfdesigner.load(data);   // === HERE ===

} else {
    wfdesigner.create();
}
```

**Comment by tlyau62** [comment]
It works great. Thanks.
